config/routes.php
<?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'view']);
    $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
    $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);


    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

Router::extensions('json', 'xml');

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/User.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Auth\DefaultPasswordHasher;

/**
 * User Entity
 *
 * @property int $id
 * @property int $unternehmen_id
 * @property string $name
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $address
 * @property string $zipcode
 * @property string $country
 * @property string $state
 * @property string $city
 * @property string $phone
 * @property string $cellphone
 * @property \Cake\I18n\Time $lastlogin
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $updated
 * @property bool $status
 *
 * @property \App\Model\Entity\Unternehmen $unternehmen
 * @property \App\Model\Entity\Application[] $applications
 * @property \App\Model\Entity\Userqualification[] $userqualifications
 */
class User extends Entity {

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];

    protected function _setPassword($password) {
        return (new DefaultPasswordHasher)->hash($password);
    }

}

src/Model/Table/ApplicationsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Applications Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Jobs
 * @property \Cake\ORM\Association\BelongsTo $Users
 *
 * @method \App\Model\Entity\Application get($primaryKey, $options = [])
 * @method \App\Model\Entity\Application newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Application[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Application|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Application patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Application[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Application findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ApplicationsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('applications');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Jobs', [
            'foreignKey' => 'job_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->numeric('desired_wage')
            ->allowEmpty('desired_wage');

        $validator
            ->integer('hours_weekly')
            ->allowEmpty('hours_weekly');

        $validator
            ->requirePresence('motivation', 'create')
            ->notEmpty('motivation');

        $validator
            ->boolean('status')
            ->allowEmpty('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['job_id'], 'Jobs'));
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;
use Cake\Mailer\Email;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 */
class UsersController extends AppController {

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index() {
        $this->paginate = [
            'contain' => ['Unternehmen']
        ];
        $users = $this->paginate($this->Users);

        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }

    /**
     * Candidates method
     *
     * @return \Cake\Network\Response|null
     */
    public function candidates() {
        $this->paginate = [
            'contain' => ['Userqualifications']
        ];

        //show only normal users
        $users = $this->paginate($this->Users->find()->where(['unternehmen_id is null']));
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);

        $this->render('index');
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null) {
        if ($id == null) { //get the user on session
            $id = $this->Auth->user('id');
        }

        $user = $this->Users->get($id, [
            'contain' => ['Unternehmen', 'Applications.Jobs.Unternehmen', 'Userqualifications.Qualifications']
        ]);

        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add() {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            $user->created = date('Y-m-d H:i:s');
            $user->user_id = $this->Auth->user('id');
            if ($this->Users->save($user)) {
                $this->Flash->success(__('Saved successfully'));

                return $this->redirect($this->referer());
            } else {
                $this->Flash->error(__('An error occurred, please try later.'));
            }
        }
        $unternehmen = $this->Users->Unternehmen->find('list', ['limit' => 200]);
        $this->set(compact('user', 'unternehmen'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null) {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->data);

            //if the user added or deleted a qualification, then ajust it on DB
            //the user can select one register or create a new one
            $qualifications = $this->Users->Userqualifications->find()->where(['user_id' => $id])->extract('qualification_id')->filter()->toArray();
            $userqualifications = array();
            if ($user->qualification_ids) {//if the user selected some qualifications
                foreach ($user->qualification_ids as $qualification) {
                    if (!in_array($qualification, $qualifications)) {
                        if (is_numeric($qualification)) {// if the user selected one 
                            $userqualification = $this->Users->Userqualifications->newEntity();
                            $userqualification->qualification_id = $qualification;
                            $userqualifications[] = $userqualification;
                        } else if (is_string($qualification)) {// is the user created another specific qualification
                            $newqualification = $this->Users->Userqualifications->Qualifications->newEntity();
                            $newqualification->description = $qualification;
                            if ($this->Users->Userqualifications->Qualifications->save($newqualification)) {
                                $userqualification = $this->Users->Userqualifications->newEntity();
                                $userqualification->qualification_id = $newqualification->id;
                                $userqualifications[] = $userqualification;
                            }
                        }
                    }
                }
                $this->Users->Userqualifications->deleteAll(['user_id' => $id, 'qualification_id NOT IN' => $user->qualification_ids]);
            } else {
                $this->Users->Userqualifications->deleteAll(['user_id' => $id]);
            }
            $user->userqualifications = $userqualifications;

            if ($this->Users->save($user)) {
                $this->Flash->success(__('Saved successfully'));

                return $this->redirect($this->referer());
            } else {
                $this->Flash->error(__('An error occurred, please try later.'));
            }
        }

        $this->loadModel('Qualifications');
        $qualifications = $this->Qualifications->find('list');
        $selectedqualifications = array_keys($this->Qualifications->find('list')->innerJoinWith('Userqualifications')->where(['Userqualifications.user_id' => $id])->toArray());

        $this->set(compact('user', 'qualifications', 'selectedqualifications'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null) {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('Removed successfully'));
        } else {
            $this->Flash->error(__('An error occurred, please try later.'));
        }

        return $this->redirect($this->referer());
    }

    public function login() {

        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                $this->registraLogin($this->Auth->user('id'));
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid Username and/or Password'));
        }
        $user = $this->Users->newEntity();
        $this->set('user', $user);
    }

    public function logout() {
        return $this->redirect($this->Auth->logout());
    }

    public function beforeFilter(Event $event) {
        parent::beforeFilter($event);
        $this->Auth->allow(['add', 'login', 'logout', 'esquecisenha', 'redefinirsenha']);
    }

    public function registraLogin($userid) {
        $user = $this->Users->get($userid);
        $user->lastlogin = date('Y-m-d H:i:s');
        $this->Users->save($user);
    }

   

}

src/Template/Users/add.ctp
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Triade Consultoria</title>
        <?= $this->Html->meta('favicon.ico', '/favicon.ico', ['type' => 'icon']) ?>

        <?= $this->Html->css('/vendors/bootstrap/dist/css/bootstrap.min.css') ?>
        <?= $this->Html->css('custom.min.css') ?>

        <?= $this->fetch('meta') ?>
        <?= $this->fetch('css') ?>    

    </head>

    <body class="login">
        <div>
            <a class="hiddenanchor" id="signin"></a>
            <a class="hiddenanchor" id="signup"></a>

            <div class="login_wrapper">
                <div class="animate form login_form">
                    <section class="login_content">
                        <?= $this->Form->create($user, ['url' => ['controller' => 'Users', 'action' => 'add']]); ?>
                        <h1>Jobbörse System</h1>
                        <div>
                            <input type="text" id="nome" name="name"  class="form-control" placeholder="Name" required="" />
                        </div>
                        <div>
                            <input type="text" id="username" name="username" class="form-control" placeholder="Username" required="" />
                        </div>
                        <div>
                            <input type="email" id="email" name="email"  class="form-control" placeholder="Email" required="" />
                        </div>
                        <div>
                            <input type="password" id="password" name="password" class="form-control" placeholder="Password" required="" />
                        </div>
                        <div>
                            <button class="btn btn-default submit" type="submit">Weiter</button>
                        </div>

                        <div class="clearfix"></div>

                        <div class="separator">
                            <p class="change_link">Hast du schon einen Account? 
                                <?= $this->Html->link(__('Dann logge dich hier ein'), ['action' => 'login']) ?>
                            </p>

                        </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </body>
</html>

src/Template/Users/index.ctp
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">         
            <div class="x_title">
                <h2><?= __('Berufstätige') ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <?= $this->Flash->render() ?>
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('name') ?></th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('email') ?></th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('zipcode') ?></th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('city') ?></th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('cellphone') ?></th>
                                <th scope="col" class="column-title"><?= $this->Paginator->sort('created') ?></th>

                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                                <th scope="col" class="column-title no-link"><span class="nobr"></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $cor = 'even';
                            foreach ($users as $user) {
                                ?>                                
                                <tr class="<?= $cor ?> pointer">

                                    <td class="a-center ">
                                        <input type="checkbox" class="flat" name="table_records" value="<?= $user->id ?>">
                                    </td>

                                    <td><?= h($user->name) ?></td>
                                    <td><?= h($user->email) ?></td>
                                    <td><?= h($user->zipcode) ?></td>
                                    <td><?= h($user->city) ?></td>
                                    <td><?= h($user->cellphone) ?></td>
                                    <td><?= h($user->created) ?></td>

                                    <td  class=" last">
                                        <div class="btn-group">
                                            <?= $this->Html->link(__('View'), ['action' => 'view', $user->id], ['class' => "btn btn-primary btn-xs"]) ?>
                                        </div>
                                    </td>
                                </tr>
                                <?php
                                $cor = $cor == 'even' ? 'odd' : 'even';
                            }
                            ?>
                        </tbody>                       
                    </table>
                    <div class="paginator">
                        <ul class="pagination">
                            <?= $this->Paginator->prev('< ' . __('previous')) ?>
                            <?= $this->Paginator->numbers() ?>
                            <?= $this->Paginator->next(__('next') . ' >') ?>
                        </ul>
                        <?= $this->Paginator->counter() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/Users/view.ctp
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">         
            <div class="x_title">
                <h2 class="green"><i class="fa fa-file"></i> Profile</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">
                <?= $this->Flash->render() ?>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="project_detail">
                        <?php if ($user->has('unternehmen')) { ?>
                            <p class="title"><?= __('Unternehmen') ?></p>
                            <p><?= $this->Html->link($user->unternehmen->name, ['controller' => 'Unternehmen', 'action' => 'view', $user->unternehmen->id]) ?></p>
                        <?php } ?>

                        <p class="title"><?= __('Name') ?></p>
                        <p><?= $user->name ? $user->name : 'keine Information'; ?></p>

                        <p class="title"><?= __('Username') ?></p>
                        <p><?= $user->username ? $user->username : 'keine Information'; ?></p>


                        <p class="title"><?= __('Email') ?></p>
                        <p><?= $user->email ? $user->email : 'keine Information'; ?></p>

                        <p class="title"><?= __('Phone') ?></p>
                        <p><?= $user->phone ? $user->phone : 'keine Information'; ?></p>

                        <p class="title"><?= __('Cellphone') ?></p>
                        <p><?= $user->cellphone ? $user->cellphone : 'keine Information'; ?></p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="project_detail">


                        <p class="title"><?= __('Address') ?></p>
                        <p><?= $user->address ? $user->address : 'keine Information'; ?></p>

                        <p class="title"><?= __('Zipcode') ?></p>
                        <p><?= $user->zipcode ? $user->zipcode : 'keine Information'; ?></p>

                        <p class="title"><?= __('Country') ?></p>
                        <p><?= $user->country ? $user->country : 'keine Information'; ?></p>

                        <p class="title"><?= __('State') ?></p>
                        <p><?= $user->state ? $user->state : 'keine Information'; ?></p>

                        <p class="title"><?= __('City') ?></p>
                        <p><?= $user->city ? $user->city : 'keine Information'; ?></p>


                    </div>
                </div>


                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="project_detail">
                        <p class="title"><?= __('Lastlogin') ?></p>
                        <p><?= $user->lastlogin ? $user->lastlogin : 'keine Information'; ?></p>


                        <p class="title"><?= __('Created') ?></p>
                        <p><?= $user->created ? $user->created : 'keine Information'; ?></p>


                        <p class="title"><?= __('Updated') ?></p>
                        <p><?= $user->updated ? $user->updated : 'keine Information'; ?></p>


                        <p class="title"><?= __('Status') ?></p>
                        <p><?= $user->status ? __('Aktiv') : __('Inaktiv'); ?></p>

                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <?= $this->Html->link("zurück", $backlink, ['class' => "btn btn-default"]) ?>
                        <?php if ($loggeduser == $user->id) { ?>
                            <?= $this->Html->link("ändern", ['action' => 'edit', $user->id], ['class' => "btn btn-primary"]) ?>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <?php if (!empty($user->userqualifications)): ?>
            <div class="x_panel">
                <div class="x_title">
                    <h2 class="green"><i class="fa fa-file"></i> Fähigkeiten und Kenntnisse </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th scope="col"  class="column-title"><?= __('Qualifikation') ?></th>
                                    <th scope="col" class="column-title no-link"><span class="nobr"></span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $cor = 'even';
                                foreach ($user->userqualifications as $userqualifications):
                                    ?>
                                    <tr class="<?= $cor ?> pointer">
                                        <td><?= h($userqualifications->qualification->description) ?></td>

                                        <td  class=" last">
                                            <div class="btn-group">
                                                <?= $this->Form->postLink(__('löschen'), ['controller' => 'Userqualifications', 'action' => 'delete', $userqualifications->id], ['class' => "btn btn-danger btn-xs", 'confirm' => __('Sind sie sicher, dass Sie es löschen möchten??', $userqualifications->id)]) ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php
                                    $cor = $cor == 'even' ? 'odd' : 'even';
                                endforeach;
                                ?>
                            </tbody>                       
                        </table>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($user->applications) && ($loggeduser == $user->id)): ?>
            <div class="x_panel">
                <div class="x_title">
                    <h2 class="green"><i class="fa fa-file"></i> Meine Bewerbung(en) </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a> </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped jambo_table bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th scope="col"  class="column-title"><?= __('Job Title') ?></th>
                                    <th scope="col"  class="column-title"><?= __('Unternehmen') ?></th>
                                    <th scope="col"  class="column-title"><?= __('Bewerbungsdatum') ?></th>
                                    <th scope="col" class="column-title no-link"><span class="nobr"></span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $cor = 'even';
                                foreach ($user->applications as $applications):
                                    ?>
                                    <tr class="<?= $cor ?> pointer">
                                        <td><?= h($applications->job->title) ?></td>
                                        <td><?= h($applications->job->unternehman->name) ?></td>
                                        <td><?= h($applications->created) ?></td>

                                        <td  class=" last">
                                            <div class="btn-group">
                                                <?= $this->Html->link(__('zeigen'), ['controller' => 'Applications', 'action' => 'view', $applications->id], ['class' => "btn btn-primary btn-xs"]) ?>
                                                <?= $this->Html->link(__('ändern'), ['controller' => 'Applications', 'action' => 'edit', $applications->id], [ 'class' => "btn btn-info btn-xs"]) ?>
                                                <?= $this->Form->postLink(__('löschen'), ['controller' => 'Applications', 'action' => 'delete', $applications->id], ['class' => "btn btn-danger btn-xs", 'confirm' => __('Sind sie sicher, dass Sie es löschen möchten??', $applications->id)]) ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php
                                    $cor = $cor == 'even' ? 'odd' : 'even';
                                endforeach;
                                ?>
                            </tbody>                       
                        </table>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>